services:
  app_prod:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - /app/node_modules/
      - /app/dist/
    command: >
      sh -c "
        npx prisma migrate deploy
        npx prisma db seed
        npm run start:dev
      "
    ports:
      - 3000:3000
    env_file: .env